site_name: Flair
repo_name: flairNLP/flair
docs_dir: resources/docs
nav:
  - Flair: README.md
  - Tutorial:
    - TUTORIAL_1_BASICS.md
    - TUTORIAL_2_TAGGING.md
    - TUTORIAL_3_WORD_EMBEDDING.md
    - TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
    - TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
    - TUTORIAL_6_CORPUS.md
    - TUTORIAL_7_TRAINING_A_MODEL.md
    - TUTORIAL_8_MODEL_OPTIMIZATION.md
    - TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md
    - TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md
  - Embeddings:
    - embeddings/BYTE_PAIR_EMBEDDINGS.md
    - embeddings/CHARACTER_EMBEDDINGS.md
    - embeddings/CLASSIC_WORD_EMBEDDINGS.md
    - embeddings/DOCUMENT_POOL_EMBEDDINGS.md
    - embeddings/DOCUMENT_RNN_EMBEDDINGS.md
    - embeddings/ELMO_EMBEDDINGS.md
    - embeddings/FASTTEXT_EMBEDDINGS.md
    - embeddings/FLAIR_EMBEDDINGS.md
    - embeddings/ONE_HOT_EMBEDDINGS.md
    - embeddings/TRANSFORMER_EMBEDDINGS.md
  - Hunflair:
    - HUNFLAIR.md
    - HUNFLAIR_CORPORA.md
    - HUNFLAIR_EXPERIMENTS.md
    - HUNFLAIR_TUTORIAL_1_TAGGING.md
    - HUNFLAIR_TUTORIAL_2_TRAINING.md
  - EXPERIMENTS.md
  - Contributing: CONTRIBUTING.md
  - CHANGELOG: CHANGELOG.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - License: https://github.com/flairNLP/flair/blob/8f9b2dc0ed199dcb0b8b8dc54478f81545ef6414/LICENSE

theme:
  name: material
  palette:
    primary: orange
  favicon: flair_logo_2020.svg
  logo: flair_logo_2020.svg
  highlightjs: true
  hljs_languages:
  - python
  - json

markdown_extensions:
  - toc:
        permalink: '#'
  - markdown.extensions.codehilite:
        guess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.highlight
  - pymdownx.superfences

